#config_version=4

modes:
    - attract
    - game
    - service

coils:
    c_test:
        number: 1
        label: First coil
    c_test2:
        number: 2
        label: Second coil

switches:
    s_door_open:
        number:
        tags: service_door_open, power_off
    s_service_enter:
        number:
        tags: service_enter
    s_service_esc:
        number:
        tags: service_esc
    s_service_up:
        number:
        tags: service_up
    s_service_down:
        number:
        tags: service_down
    s_test:
        number:
        label: "The test switch label"

sound_system:
  tracks:
    voice:
      volume: 1
      priority: 2
      simultaneous_sounds: 1
      preload: true
    sfx:
      volume: 1
      priority: 1
      preload: true
      simultaneous_sounds: 7
    music:
      volume: 0.5
      simultaneous_sounds: 1
  buffer: 2048  # previous value was 512
  frequency: 44100
  channels: 1
  master_volume: 0.8
  enabled: true

physical_dmds:
  default:
    shades: 16
    fps: 24

window:
  width: 600
  height: 200
  title: Service Test
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true

displays:
  window:
    height: 200
    width: 600
  dmd:
    width: 128
    height: 32
    default: true

slides:
  window_slide_1:
  - type: dmd
    width: 512
    height: 128
    pixel_color: ff5500
    dark_color: 220000
    z: 1
  - type: text
    text: MISSION PINBALL FRAMEWORK
    anchor_y: top
    y: top-3
    font_size: 30
    z: 1
    color: white
  - type: rectangle
    width: 514
    height: 130
    z: 2
    color: 444444

  waiting_for_connection:
  - type: text
    text: WAITING FOR MPF CONNECTION

  asset_status:
  - type: text
    text: "LOADING ASSETS: (percent)%"

slide_player:
  mc_ready:
    window_slide_1:
      target: window
  loading_assets: asset_status

widget_styles:
  text_default:
    font_size: 10
    adjust_top: 2
    adjust_bottom: 3
  medium:
    font_size: 8
    adjust_top: 1
    adjust_bottom: 1
  small:
    font_size: 9
    adjust_top: 2
    adjust_bottom: 3
