# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.30.1.dev1582+g4de473b.d20220808'
__version_tuple__ = version_tuple = (0, 30, 1, 'dev1582', 'g4de473b.d20220808')
